const state={lang:localStorage.getItem('may.lang')||'ja',view:(location.hash||'#profile').slice(1),tweets:[],ko:{},profile:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I18N={ja:{profile:'プロフィール',twitter:'X アーカイブ',archiveLead:'@May_o_o_T の投稿を時系列で保存したアーカイブ',search:'投稿を検索',tweets:'件の投稿',source:'公式プロフィール',sourceNote:'アミューズ公式プロフィールをもとに整理しています。',openSource:'アミューズ公式ページを開く ↗',voice:'ボイスサンプル',footer:'非公式アーカイブ。権利は各権利者に帰属します。',noResult:'一致する投稿がありません。',mediaMissing:'メディアは別ストレージ接続後に表示されます。',reply:'返信',retweet:'リポスト',like:'いいね',views:'表示'},ko:{profile:'프로필',twitter:'X 아카이브',archiveLead:'@May_o_o_T의 게시물을 시간순으로 보존한 아카이브',search:'게시물 검색',tweets:'개 게시물',source:'공식 프로필',sourceNote:'아뮤즈 공식 프로필을 바탕으로 정리했습니다.',openSource:'아뮤즈 공식 페이지 열기 ↗',voice:'보이스 샘플',footer:'비공식 아카이브입니다. 각 콘텐츠의 권리는 해당 권리자에게 있습니다.',noResult:'검색 결과가 없습니다.',mediaMissing:'미디어는 별도 스토리지 연결 후 표시됩니다.',reply:'답글',retweet:'리포스트',like:'좋아요',views:'조회'}};
function t(k){return I18N[state.lang][k]}
function setLang(lang){state.lang=lang;localStorage.setItem('may.lang',lang);document.documentElement.lang=lang;$$('.lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderChrome();renderProfile();renderTweets()}
function setView(view){state.view=view==='twitter'?'twitter':'profile';location.hash=state.view;$('#profileView').classList.toggle('hidden',state.view!=='profile');$('#twitterView').classList.toggle('hidden',state.view!=='twitter');$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}
function renderChrome(){$('#tabProfile').textContent=t('profile');$('#tabTwitter').textContent=t('twitter');$('#archiveTitle').textContent=t('twitter');$('#archiveLead').textContent=t('archiveLead');$('#q').placeholder=t('search');$('#footerText').textContent=t('footer');document.title=state.lang==='ko'?'May Archive — 타치바나 메이':'May Archive — 橘めい'}
function renderProfile(){if(!state.profile)return;const p=state.profile,L=state.lang;const fields=p.fields.map(f=>`<div class="profile-field"><dt>${esc(f['label_'+L])}</dt><dd>${esc(f['value_'+L])}</dd></div>`).join('');const voices=(p['voice_samples_'+L]||[]).map(x=>`<span class="voice-item">${esc(x)}</span>`).join('');$('#profileView').innerHTML=`<div class="profile-hero"><div class="eyebrow">${esc(p['affiliation_'+L])}</div><h1>${esc(p['name_'+L])}</h1><p class="romanized">${esc(p.romanized)}</p><div class="chips"><span class="chip">${esc(p['occupation_'+L])}</span></div></div><dl class="profile-grid">${fields}</dl><section class="voice-card"><h2>${t('voice')}</h2><div class="voice-list">${voices}</div></section><section class="source-card"><h2>${t('source')}</h2><p class="muted">${t('sourceNote')}</p><a href="${esc(p.source_url)}" target="_blank" rel="noopener">${t('openSource')}</a></section>`}
function mediaHtml(x){if(!x.media?.length)return'';const items=x.media.map(m=>/\.mp4$/i.test(m)?`<video controls preload="metadata" src="${encodeURI(m)}" onerror="this.style.display='none';this.parentElement.nextElementSibling.style.display='block'"></video>`:`<img loading="lazy" src="${encodeURI(m)}" alt="" onerror="this.style.display='none';this.parentElement.nextElementSibling.style.display='block'">`).join('');return `<div class="media">${items}</div><div class="media-missing">${t('mediaMissing')}</div>`}
function renderTweets(){if(!state.tweets.length)return;const q=$('#q').value.trim().toLowerCase();const list=state.tweets.filter(x=>{const text=(state.lang==='ko'?(state.ko[x.id]||x.content):x.content)||'';return text.toLowerCase().includes(q)});$('#count').textContent=`${list.length}${t('tweets')}`;if(!list.length){$('#feed').innerHTML=`<div class="empty">${t('noResult')}</div>`;return}$('#feed').innerHTML=list.map(x=>{const body=state.lang==='ko'?(state.ko[x.id]||x.content):x.content;return `<article class="tweet" id="tweet-${x.id}"><div class="tweet-top"><span class="name">${esc(state.lang==='ko'?'타치바나 메이':x.name)}</span><span class="handle">@${esc(x.handle)}</span><span class="date">· ${esc(x.date.slice(0,16))}</span><a class="orig" target="_blank" rel="noopener" href="https://x.com/${encodeURIComponent(x.handle)}/status/${x.id}">X ↗</a></div><div class="tweet-text">${esc(body)}</div>${mediaHtml(x)}<div class="stats"><span>${t('reply')} ${x.reply}</span><span>${t('retweet')} ${x.retweet}</span><span>${t('like')} ${x.favorite}</span><span>${t('views')} ${x.views}</span></div></article>`}).join('')}
async function load(){const manifest=await fetch('data/manifest.json').then(r=>r.json());const [profile,tweetParts,koParts]=await Promise.all([fetch('profile.json').then(r=>r.json()),Promise.all(manifest.tweet_files.map(f=>fetch(f).then(r=>r.json()))),Promise.all(manifest.ko_files.map(f=>fetch(f).then(r=>r.json())))]);state.profile=profile;state.tweets=tweetParts.flat().sort((a,b)=>b.date.localeCompare(a.date));state.ko=Object.assign({},...koParts);setLang(state.lang);setView(state.view);renderTweets()}
$$('.lang-switch button').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));$$('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#q').oninput=renderTweets;window.addEventListener('hashchange',()=>setView((location.hash||'#profile').slice(1)));load().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend',`<p class="empty">${esc(err.message)}</p>`)})
