const state={lang:localStorage.getItem('may.lang')||'ja',view:(location.hash||'#profile').slice(1),tweets:[],ko:{},profile:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const I18N={ja:{profile:'プロフィール',twitter:'X アーカイブ',archiveLead:'@May_o_o_T の投稿。保存メディアが未接続の投稿は公式X埋め込みを表示します。',search:'投稿を検索',tweets:'件の投稿',source:'公式プロフィール',sourceNote:'アミューズ公式プロフィールをもとに整理しています。',openSource:'アミューズ公式ページを開く ↗',voice:'ボイスサンプル',voiceNote:'音声はアミューズ公式ページで再生できます。',playOfficial:'公式ページで再生 ↗',footer:'非公式アーカイブ。権利は各権利者に帰属します。',noResult:'一致する投稿がありません。',reply:'返信',retweet:'リポスト',like:'いいね',views:'表示',photo:'公式プロフィール写真'},ko:{profile:'프로필',twitter:'X 아카이브',archiveLead:'@May_o_o_T 게시물입니다. 저장 미디어가 아직 연결되지 않은 게시물은 공식 X 임베드로 표시합니다.',search:'게시물 검색',tweets:'개 게시물',source:'공식 프로필',sourceNote:'아뮤즈 공식 프로필을 바탕으로 정리했습니다.',openSource:'아뮤즈 공식 페이지 열기 ↗',voice:'보이스 샘플',voiceNote:'음성은 아뮤즈 공식 페이지에서 직접 재생할 수 있습니다.',playOfficial:'공식 페이지에서 재생 ↗',footer:'비공식 아카이브입니다. 각 콘텐츠의 권리는 해당 권리자에게 있습니다.',noResult:'검색 결과가 없습니다.',reply:'답글',retweet:'리포스트',like:'좋아요',views:'조회',photo:'공식 프로필 사진'}};
function t(k){return I18N[state.lang][k]}
function setLang(lang){state.lang=lang;localStorage.setItem('may.lang',lang);document.documentElement.lang=lang;$$('.lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderChrome();renderProfile();renderTweets()}
function setView(view){state.view=view==='twitter'?'twitter':'profile';location.hash=state.view;$('#profileView').classList.toggle('hidden',state.view!=='profile');$('#twitterView').classList.toggle('hidden',state.view!=='twitter');$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));if(state.view==='twitter'&&window.twttr?.widgets) setTimeout(()=>twttr.widgets.load($('#feed')),50)}
function renderChrome(){$('#tabProfile').textContent=t('profile');$('#tabTwitter').textContent=t('twitter');$('#archiveTitle').textContent=t('twitter');$('#archiveLead').textContent=t('archiveLead');$('#q').placeholder=t('search');$('#footerText').textContent=t('footer');document.title=state.lang==='ko'?'May Archive — 타치바나 메이':'May Archive — 橘めい'}
function renderProfile(){if(!state.profile)return;const p=state.profile,L=state.lang;const fields=p.fields.map(f=>`<div class="profile-field"><dt>${esc(f['label_'+L])}</dt><dd>${esc(f['value_'+L])}</dd></div>`).join('');const voices=(p['voice_samples_'+L]||[]).map(x=>`<a class="voice-item voice-link" href="${esc(p.source_url)}" target="_blank" rel="noopener">${esc(x)} <span>↗</span></a>`).join('');$('#profileView').innerHTML=`<section class="profile-shell"><div class="profile-photo-wrap"><img class="profile-photo" src="https://www.amuse.co.jp/artist/33ecf604aff3dad2966f36c3cd470e3bf2b8ad04.jpg" referrerpolicy="no-referrer" alt="${t('photo')}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><a class="photo-fallback" href="${esc(p.source_url)}" target="_blank" rel="noopener">${t('photo')}<br>AMUSE ↗</a></div><div class="profile-copy"><div class="eyebrow">${esc(p['affiliation_'+L])}</div><h1>${esc(p['name_'+L])}</h1><p class="romanized">${esc(p.romanized)}</p><div class="chips"><span class="chip">${esc(p['occupation_'+L])}</span></div></div></section><dl class="profile-grid">${fields}</dl><section class="voice-card"><div class="section-head"><div><h2>${t('voice')}</h2><p class="muted">${t('voiceNote')}</p></div><a href="${esc(p.source_url)}" target="_blank" rel="noopener">${t('playOfficial')}</a></div><div class="voice-list">${voices}</div></section><section class="source-card"><h2>${t('source')}</h2><p class="muted">${t('sourceNote')}</p><a href="${esc(p.source_url)}" target="_blank" rel="noopener">${t('openSource')}</a></section>`}
function archivedMediaHtml(x){if(!x.media?.length)return'';return `<div class="media archived-media">${x.media.map(m=>/\.mp4$/i.test(m)?`<video controls preload="metadata" src="${encodeURI(m)}"></video>`:`<img loading="lazy" src="${encodeURI(m)}" alt="">`).join('')}</div>`}
function xEmbed(x){return `<div class="x-embed"><blockquote class="twitter-tweet" data-theme="dark" data-dnt="true"><a href="https://twitter.com/${encodeURIComponent(x.handle)}/status/${encodeURIComponent(x.id)}">View post on X</a></blockquote></div>`}
function renderTweets(){if(!state.tweets.length)return;const q=$('#q').value.trim().toLowerCase();const list=state.tweets.filter(x=>{const body=(state.lang==='ko'?(state.ko[x.id]||x.content):x.content)||'';return (body+' '+x.content).toLowerCase().includes(q)});$('#count').textContent=`${list.length}${t('tweets')}`;if(!list.length){$('#feed').innerHTML=`<div class="empty">${t('noResult')}</div>`;return}$('#feed').innerHTML=list.map(x=>{const body=state.lang==='ko'?(state.ko[x.id]||x.content):x.content;return `<article class="tweet" id="tweet-${x.id}"><div class="tweet-top"><span class="name">${esc(state.lang==='ko'?'타치바나 메이':x.name)}</span><span class="handle">@${esc(x.handle)}</span><span class="date">· ${esc(x.date.slice(0,16))}</span><a class="orig" target="_blank" rel="noopener" href="https://x.com/${encodeURIComponent(x.handle)}/status/${x.id}">X ↗</a></div><div class="tweet-text">${esc(body)}</div>${archivedMediaHtml(x)}${x.media?.length?'':xEmbed(x)}<div class="stats"><span>${t('reply')} ${x.reply}</span><span>${t('retweet')} ${x.retweet}</span><span>${t('like')} ${x.favorite}</span><span>${t('views')} ${x.views}</span></div></article>`}).join('');if(window.twttr?.widgets)setTimeout(()=>twttr.widgets.load($('#feed')),0)}
async function load(){const manifest=await fetch('data/manifest.json',{cache:'no-store'}).then(r=>r.json());const [profile,tweetParts,koParts]=await Promise.all([fetch('profile.json',{cache:'no-store'}).then(r=>r.json()),Promise.all(manifest.tweet_files.map(f=>fetch(f,{cache:'no-store'}).then(r=>r.json()))),Promise.all(manifest.ko_files.map(f=>fetch(f,{cache:'no-store'}).then(r=>r.json())))]);state.profile=profile;state.tweets=tweetParts.flat().sort((a,b)=>b.date.localeCompare(a.date));state.ko=Object.assign({},...koParts);setLang(state.lang);setView(state.view)}
$$('.lang-switch button').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));$$('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#q').oninput=renderTweets;window.addEventListener('hashchange',()=>setView((location.hash||'#profile').slice(1)));load().catch(err=>{console.error(err);document.body.insertAdjacentHTML('beforeend',`<p class="empty">${esc(err.message)}</p>`)})
